#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MeetupManager.Droid.Resource", IsApplication=true)]

namespace MeetupManager.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::MeetupManager.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::MeetupManager.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::MeetupManager.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000b
			public const int accent = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int background = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int bar_down = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int bar_up = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int divider = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int icons = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int pop = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int primary = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int primary_dark = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int primary_light = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int primary_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int secondary_text = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int xam_blue = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int xam_darkblue = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int xam_green = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int xam_purple = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int standard_padding = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_navigation_arrow_forward = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_settings = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_social_person_add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_toggle_check_box = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_toggle_check_box_outline_blank = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_trending_up = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_winner = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_meetup = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int name = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int event_columns = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int group_columns = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int member_columns = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_add_member = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int about = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int cancel = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7f050015
			public const int limit_events = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int logging_in = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int login = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int login_details = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int menu_about = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int menu_add_new_member = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int menu_refresh = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int menu_refresh_login = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int menu_select_winner = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int menu_settings = 2131034117;
			
			// aapt resource value: 0x7f050016
			public const int menu_stats = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int new_member = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int ok = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int popup_name = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int show_all_events = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int tap_to_login = 2131034126;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int MyTheme = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int MyTheme_ActionBar_TitleTextStyle = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int MyTheme_ActionBarStyle = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int MyTheme_Base = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences_general = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
